# Generated by Django 4.0.5 on 2022-06-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teniashiapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_num',
            field=models.CharField(max_length=3),
        ),
    ]
